### PR TITLE
[0017] Add Sentry gem

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
Sentry alerts

`SENTRY_DSN ` has been added as a Github Secret

### Changes proposed in this pull request
- Add sentry gem

### Guidance to review
🚢

### CODE REVIEW

**Comment by defong** [comment]
[Setup Sentry](https://trello.com/c/0LLkFhnr/17-setup-sentry)

**Review by defong — APPROVED** [review]
PR number 1, always get approved

**Comment by aliuk2012** [comment]
@defong its not testable because the build is broken... ;)

**Comment by defong** [comment]
> @defong its not testable because the build is broken... ;)

It's @dankmitchell codes... what can i say? ¯\_(ツ)_/¯

**Pull request merged**
