### PR TITLE
39 fix terraform deployment

### PR DESCRIPTION
**Pull request by felixtheflex**
### Context

Pass variable between build steps
Set the status of application deployed to Paas to "Started". This was previously set to false.

### CODE REVIEW

**Review by saliceti — APPROVED** [review]
OK

**Comment by misaka** [comment]
Is now a good time to move the deploy part to a separate file workflow file, as we mentioned we'd do in a previous PR?

**Review by misaka — COMMENTED** [review]
Create a `deploy.yml` workflow file?

**Comment by saliceti** [comment]
> Is now a good time to move the deploy part to a separate file workflow file, as we mentioned we'd do in a previous PR?

We could but it feels like early optimisation. Can we wait for a use case?

**Comment by misaka** [comment]
> > Is now a good time to move the deploy part to a separate file workflow file, as we mentioned we'd do in a previous PR?
> 
> We could but it feels like early optimisation. Can we wait for a use case?

I'm not sure what the use case or optimisation would be. I thought it would make sense organisation-wise ... one workflow per file.

**Review by misaka — APPROVED** [review]
Still think one workflow per file would make sense, but am happy for this to be merged and we can discuss OOB.

**Pull request merged**
